name: XZ CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn' # 或 'npm'

      - name: Install dependencies
        run: yarn install --frozen-lockfile # 或 npm ci

      # 1. TypeScript 类型检查
      - name: TypeScript Compilation
        run: yarn vue-tsc --noEmit

      # 2. ESLint 检查
      - name: Run ESLint
        run: yarn eslint 'src/**/*.{ts,tsx,vue}' --max-warnings=0

#      # 3. 单元测试（Jest）
#      - name: Run Unit Tests
#        run: yarn test --coverage
#        env:
#          NODE_ENV: test

#      # 4. 上传测试覆盖率
#      - name: Upload Coverage
#        uses: codecov/codecov-action@v3

  build-and-deploy:
    name: Build & Deploy
    needs: lint-and-test # 依赖 lint-and-test 成功后才执行
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # 仅 main 分支触发部署
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 5. 构建生产包
      - name: Build Production
        run: yarn build
        env:
          NODE_ENV: production

      # 6. 部署到 Vercel（或其他平台）
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.XZ }}