name: GitHub Actions Demo
on: [push]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        if: runner.os != 'Windows'
        uses: actions/checkout@v2

      - name: ESLintCode
        uses: actions/setup-node@v2
      - run: yarn
      - run: yarn global add eslint && eslint ./src/*/**.ts

      - name: StyleLintCode
        uses: actions/setup-node@v2
      - run: yarn
      - run: yarn global add stylelint && stylelint ./src/*/**.scss

  Build:
    needs: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v2
        env:
          ACCESS_TOKEN: ${{ secrets.XZ }}
          BRANCH: main
      - run: yarn
      - run: yarn build:pre