name: XZ CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 1. TypeScript 类型检查
      - name: TypeScript Compilation
        run: yarn vue-tsc --noEmit

      # 2. ESLint 检查 (uncommented)
      - name: Run ESLint
        run: yarn eslint 'src/**/*.{ts,tsx,vue}' --max-warnings=0

  build-and-deploy:
    name: Build & Deploy
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 5. 构建生产包
      - name: Build Production
        run: yarn build
        env:
          NODE_ENV: production

      # 6. 部署到 Vercel（完整配置）
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.XZ }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'
